name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up node
      uses: actions/setup-node@v4
    - name: Install dependencies
      run: |
        npm install
    - name: Run svelte check and linting
      run: |
        npm run check
        npm run lint
      env:
        GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
        GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
    - name: Run tests
      run: |
        npm run test
